[object]
name = "sp.clustertrain"
module = "SP-Tools"
category = ""
digest = "Create clusters based on input analysis"
seealso =  ['sp.classtrain', 'sp.clustertrain', 'sp.classifierdisplay']
description = "Finds the nearest match based on pre-trained classes/clusters"
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.classtrain</o> object will create a classifier based on incoming class labels and descriptor analysis. The labels can be the default Sensory Percussion labels or any arbitrary input.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="o>buffer~</o> and control in"
description="Incoming <o>buffer~</o> of descriptors to analyze for cluster matching. Also takes the messages for object control."

[outlets]
[outlets.0]
type="list"
digest="Dict out for visualization"
description="<o>dict</o> output for displaying in <o>sp.plotter</o>."

[outlets.1]
type="int"
digest="Amount of entries"
description="Total amount of entries that have been sent to the clustering algorithm."

[messages.print]
digest = "Print dataset contents to Max console"
description = "Prints a summary of the descriptors in the dataset to the Max console."

[messages.write]
digest = "Write training to disk"
description = "Write a <b>.json</b> file with all the descriptors and cluster labels to disk."

[messages.clear]
digest = "Clears the analyzed data"
description = "Clears the analyzed data."

[messages.reset]
digest = "Resets the analyzed data"
description = "Resets the analyzed data."

[messages.clusters]
digest = "Amount of clusters to create"
description = "The amount of clusters to find in the current training data."