[object]
name = "sp.corpusanalysis"
module = "SP-Tools"
category = ""
digest = "Analyze all the samples in a folder"
seealso =  ['sp.corpuscreate', 'sp.corpusmatch', 'sp.gridmatch', 'sp.corpusplayer~', 'sp.corpuslist', 'sp.folderloop']
description = "Analyze all the samples in a folder to create a corpus."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.corpusanalysis</o> object works in conjunction with <o>sp.folderloop<o/> to analyze all the samples in a folder for a variety of descriptors, timeframes, and metadata to be used in <o>sp.corpusmatch<o/>. Keeps track of the location of the samples when analyzed.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Control in"
description="Control input."

[outlets]
[outlets.0]
type="list"
digest="Bang when single file analysis is complete"
description="Bang when single file analysis is complete."

[outlets.1]
type="list"
digest="<o>dict</o> output for <o>sp.plotter</o>"
description="<o>dict</o> output for <o>sp.plotter</o>."

[messages.clear]
digest = "Clears the analysis"
description = "Clears the analysis."

[messages.reset]
digest = "Resets the analysis"
description = "Resets the analysis."

[messages.write]
digest = "Write corpus analysis to disk"
description = "Write a <b>.json</b> file with all the descriptors and required metadata to disk."

[messages.print]
digest = "Print dataset contents to Max console"
description = "Prints a summary of the descriptors in the dataset to the Max console."

[messages.done]
digest = "Significy that analysis is complete"
description = "Signifies that analysis is complete to compute summary statistics."

[messages.bang]
digest = "Analyze loaded file"
description = "Analyze loaded audio file."

[messages.path]
digest = "Path of the current loaded sample"
description = "Path of the current loaded sample passed along from <o>sp.folderloop</o>."

[messages.buffer]
digest = "Randomly generated <o>buffer~</o> name"
description = "Randomly generated <o>buffer~</o> name from <o>sp.folderloop</o>."