[object]
name = "sp.concatmatch"
module = "SP-Tools"
category = ""
digest = "Find the nearest match in a pre-analyzed corpus"
seealso =  ['sp.classtrain', 'sp.clustertrain', 'sp.classifierdisplay']
description = "Find the nearest match in a pre-analyzed concat corpus."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.concatmatch</o> object works in conjunction with <o>sp.concatanalysis~</o> and <o>sp.concatplayer~</o> to create real-time audio mosaicking via concatatenative synthesis with a pre-analyzed concat corpus. <o>sp.concatmatch</o> handles the nearest neighbor matching.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="<o>buffer~</o> and control in"
description="Takes incoming <o>buffer~</o> name to find the nearest entry, as well as handling all <m>message</m> inputs."

[outlets]
[outlets.0]
type="list"
digest="Matched entry"
description="The nearest entry in the pre-trained concat corpus."

[outlets.1]
type="list"
digest="Position and name outlet for <o>waveform~</o>"
description="Sends the <o>buffer~</o> name and playback position to be used with <o>waveform~</o>."

[messages.load]
digest = "Load a pre-trained concat <b>.json</b> file"
description = "Opens file dialog to select pre-trained concat <b>.json</b> file."

[messages.read]
digest = "Read a pre-trained concat <b>.json</b> file"
description = "Reads a pre-trained concat <b>.json</b> file directly from a relative or absolute path."

[messages.print]
digest = "Print summary info to Max console"
description = "Prints summary info including overall statistics to the Max console."

[messages.rate]
digest = "Rate of concatenation"
description = "Rate of matching/playback in <b>ms</b> in the concatenation engine."