[object]
name = "sp.corpuscreate"
module = "SP-Tools"
category = ""
digest = "Creates a corpus based on a folder of samples"
seealso =  ['sp.corpusanalysis', 'sp.corpusmatch', 'sp.gridmatch', 'sp.corpusplayer~', 'sp.corpuslist', 'sp.folderloop']
description = "Creates a corpus based on a folder of samples."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>Analyze all the samples in a folder for a variety of descriptors, timeframes, and metadata. Keeps track of the location of the samples when analyzed.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Control in"
description="Control input."

[outlets]
[outlets.0]
type="list"
digest="<o>dict</o> output for <o>sp.plotter</o>"
description="<o>dict</o> output for <o>sp.plotter</o>."

[outlets.1]
type="list"
digest="Total duration output"
description="Total duration of analysis in <b>ms</b> output."

[messages.load]
digest = "Load a folder of samples to analyze"
description = "Loads a folder of samples to analyze."

[messages.read]
digest = "Read a folder of samples to analyze"
description = "Reads a folder of samples to analyze directly from a relative or absolute path."

[messages.clear]
digest = "Clears the analysis"
description = "Clears the analysis."

[messages.reset]
digest = "Resets the analysis"
description = "Resets the analysis."

[messages.write]
digest = "Write corpus analysis to disk"
description = "Write a <b>.json</b> file with all the descriptors and required metadata to disk."

[messages.print]
digest = "Print dataset contents to Max console"
description = "Prints a summary of the descriptors in the dataset to the Max console."