[object]
name = "sp.classtrain"
module = "SP-Tools"
category = ""
digest = "Create classes based on input analysis"
seealso =  ['sp.classtrain', 'sp.clustertrain', 'sp.classifierdisplay']
description = "Finds the nearest match based on pre-trained classes/clusters."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.classtrain</o> object will create a classifier based on incoming class labels and descriptor analysis. The labels can be the default <b>Sensory Percussion</b> labels or any arbitrary input.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="<o>buffer~</o> and control in"
description="Incoming <o>buffer~</o> of descriptors to attach to the current label/class. Also takes the messages for object control."

[outlets]
[outlets.0]
type="list"
digest="Matched class"
description="The nearest match in the pre-trained classifier."

[outlets.1]
type="int"
digest="Amount of entries"
description="Total amount of entries that have been sent to the classifier."

[messages.class]
digest = "Class label to train"
description = "The label you want to apply to the incoming entries."

[messages.clear]
digest = "Clears the loaded classifer"
description = "Clears the loaded classifer."

[messages.print]
digest = "Print dataset contents to Max console"
description = "Prints a summary of the descriptors in the dataset to the Max console."

[messages.reset]
digest = "Resets the loaded classifier"
description = "Resets the loaded classifier."

[messages.train]
digest = "Enable classifier training"
description = "Enables the training mode for the internal classifier."

[messages.write]
digest = "Write training to disk"
description = "Write a <b>.json</b> file with all the descriptors and class labels to disk."