[object]
name = "sp.controllers"
module = "SP-Tools"
category = ""
digest = "Extract meta-parameters from descriptors"
seealso =  ['sp.speed', 'sp.descriptors~', 'sp.descriptorframe']
description = "Extracts meta-parameters from descriptors."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.controllers</o> object works in conjuntion with <o>sp.descriptors~</o>/<o>sp.descriptorframe</o> to create several meta-parameters based on loudness and centroid (brightness). </p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Descriptor and control in"
description="Descriptor and control input."

[outlets]
[outlets.0]
type="list"
digest="Controllers out"
description="Controllers meta-parameter output."

[messages.calibrate]
digest = "Enables scaling calibration"
description = "Enables manual calibration of descriptor ranges."

[messages.reset]
digest = "Resets manual calibration"
description = "Resets manual calibration and returns to auto-calibration routine."

[attributes]
[attributes.history]
digest = "Amount of values to compute on parameters on"
description = "Amount of values to compute on parameters on."
default = { value=7, type="int", size=1 }