[object]
name = "sp.concatanalysis~"
module = "SP-Tools"
category = ""
digest = "Descriptor analysis for real-time mosaicking"
seealso =  ['sp.concatcreate', 'sp.concatmatch', 'sp.concatplayer~', 'sp.concatsynth~']
description = "Finds the nearest match based on pre-trained classes/clusters."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.concatanalysis~</o> object is based on <o>sp.descrptorsrt~~</o> but has all of the appropriate settings pre-baked so it can get sent directly to <o>sp.concatmatch</o>. It also takes some playback controls via <m>rate</m> and <m>random</m> messages.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="signal"
digest="Audio and control in"
description="Audio input to be analyzed for concatenation/resynthesis."

[outlets]
[outlets.0]
type="list"
digest="Descriptors and statistics output as <o>buffer~</o>"
description="The nearest match in the pre-trained classifier."

[outlets.1]
type="list"
digest="Current rate"
description="Current rate in <b>ms</b> of the internal clocking."

[messages.random]
digest = "Enable random rate matching"
description = "Enable random variation to the matching/concatenation."

[messages.rate]
digest = "Rate of concatenation"
description = "Rate of matching/playback in <b>ms</b> in the concatenation engine."

[attributes]
[attributes.random]
digest = "Enable random rate matching"
description = "Enable random variation to the matching/concatenation."
default = { value=0, type="int", size=1 }

[attributes.rate]
digest = "Rate of concatenation"
description = "Rate of matching/playback in <b>ms</b> in the concatenation engine."
default = { value=100.0, type="float", size=1 }