[object]
name = "sp.crossbank~"
module = "SP-Tools"
category = ""
digest = "Cascade of <o>cross~</o> filters"
seealso =  ['sp.corpusplayer~', 'sp.playbackcore~', 'sp.corpusmatch', 'poly~']
description = "Cascade of <o>cross~</o> filters."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.crossbank~</o> object is a cascade of <o>cross~</o> filters for spectral compensation. Frequencies are pre-set to adjust the spectrum based on the melband analysis/compensation. It should be used inside a <o>poly~</o> object.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="signal"
digest="Audio in"
description="Audio input to be analyzed for concatenation/resynthesis."

[outlets]
[outlets.0]
type="signal"
digest="Audio output"
description="Audio output."