[object]
name = "sp.datalooper~"
module = "SP-Tools"
category = ""
digest = "Record, loop, and play back descriptor data"
seealso =  ['sp.databending', 'sp.datadelay', 'sp.datagranular', 'sp.datatranspose', 'sp.descriptors~', 'sp.descriotorframe']
description = "Record, loop, and play back descriptor data."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.datalooper~</o> object takes incoming descriptor data (descriptors, melbands, or MFCCs) and sends them into a looper with somewhat conventional looper controls. The input can be lists or <o>buffer~</o>s and the same will be output.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Descriptor and control in"
description="Incoming descriptors as a list or <o>buffer~</o> as well as control input."

[outlets]
[outlets.0]
type="list"
digest="Descriptor output"
description="Transformed descriptor output."

[outlets.1]
type="signal"
digest="Loop sync output"
description="Current loop position."

[messages.clear]
digest = "Clears the recorded loop"
description = "Clears the recorded loop and stops playback."

[messages.duration]
digest = "Maximum duration for loop 'buffer'"
description = "The maxmimum amount of time that you can record into the 'buffer', in <b>ms</b>."

[messages.end]
digest = "Stops recording and sets loop length"
description = "Stops recording and sets the loop length."

[messages.play]
digest = "Play recorded loop"
description = "Plays recorded loop."

[messages.record]
digest = "Records a new loop"
description = "Records a new loop."

[messages.speed]
digest = "Playback speed of recorded loop"
description = "Playback speed of recorded loop in <b>ms</b>."

[messages.stop]
digest = "Stops playback"
description = "Stops playback."

[attributes.duration]
digest = "Maximum duration for loop 'buffer'"
description = "The maxmimum amount of time that you can record into the 'buffer', in <b>ms</b>."
default = { value=30000, type="float64", size=1 }