[object]
name = "sp.descriptordisplay"
module = "SP-Tools"
category = ""
digest = "Displays the descriptors as a radar chart"
seealso =  ['sp.descriptorframe', 'sp.descriptors~', 'sp.descriptorsrt~', 'sp.onsetframe~', 'sp.realtimeframe~']
description = "Displays the descriptors as a radar chart."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.descriptordisplay</o> object plots the incoming realtime descriptors, along with the nearest match on a radar chart for visualizing the differences between the incoming audio and its nearest match.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Descriptor input"
description="Incoming descriptors as a list or <o>buffer~</o>."

[inlets.1]
type="list"
digest="Matched entry from <o>sp.corpusmatch</o>"
description="Matched entry from <o>sp.corpusmatch</o>."