[object]
name = "sp.datadelay"
module = "SP-Tools"
category = ""
digest = "Delays incoming descriptor data like a lossy 'analog' delay"
seealso =  ['sp.databending', 'sp.datagranular', 'sp.datalooper~', 'sp.datatranspose', 'sp.descriptors~', 'sp.descriotorframe']
description = "Delays incoming descriptor data like a lossy 'analog' delay."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.datadelay</o> object takes incoming descriptors (of any kind) and sends them through a delay line. The feedback and rolloff parameters function as they would in a conventional delay. The input can be lists or <o>buffer~</o>s and the same will be output.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Descriptor and control in"
description="Incoming descriptors as a list or <o>buffer~</o> as well as control input."

[outlets]
[outlets.0]
type="list"
digest="Descriptor output"
description="Transformed descriptor output."

[messages.clear]
digest = "Clear the delay line"
description = "Clear the delay line."

[messages.delay]
digest = "Delay time"
description = "Delay time in <b>ms</b>."

[messages.feedback]
digest = "Feedback amount"
description = "Amount of feedback in the delay line in <b>%</b>."

[messages.rolloff]
digest = "Amount of 'highs' to rolloff"
description = "Amount of 'highs' to rolloff on input and in feedback path, in <b>%</b>."

[messages.threshold]
digest = "Threshold for material to be not sent back into delay line"
description = "Threshold for material to be not sent back into the feedback loop in <b>dB</b>."

[attributes.delay]
digest = "Delay time"
description = "Delay time in <b>ms</b>."
default = { value=130, type="float64", size=1 }

[attributes.feedback]
digest = "Feedback amount"
description = "Amount of feedback in the delay line in <b>%</b>."
default = { value=50, type="float64", size=1 }

[attributes.rolloff]
digest = "Amount of 'highs' to rolloff"
description = "Amount of 'highs' to rolloff on input and in feedback path, in <b>%</b>."
default = { value=80, type="float64", size=1 }

[attributes.threshold]
digest = "Threshold for material to be not sent back into delay line"
description = "Threshold for material to be not sent back into the feedback loop in <b>dB</b>."
default = { value=-70, type="float64", size=1 }