[object]
name = "sp.datagranular"
module = "SP-Tools"
category = ""
digest = "Repeat and vary incoming descriptor data like a 'granular synth'"
seealso =  ['sp.databending', 'sp.datadelay', 'sp.datalooper~', 'sp.datatranspose', 'sp.descriptors~', 'sp.descriotorframe']
description = "Repeat and vary incoming descriptor data like a 'granular synth'."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.datagranular</o> object takes incoming descriptor data (descriptors, melbands, or MFCCs) and processes it through a 'granular synth'-style process. The input can be lists or <o>buffer~</o>s and the same will be output.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Descriptor and control in"
description="Incoming descriptors as a list or <o>buffer~</o> as well as control input."

[outlets]
[outlets.0]
type="list"
digest="Descriptor output"
description="Transformed descriptor output."

[messages.enable]
digest = "Enable the granular process"
description = "Enables/disables the granular process."

[messages.random]
digest = "Enable random timing in the <m>rate</m>"
description = "Enable random timing variations in the <m>rate</m>."

[messages.rate]
digest = "Rate of repetition"
description = "Rate of the repetition in <b>ms</b>."

[messages.variation]
digest = "Amount of variation in each repetition"
description = "Amount of variation in each repeating 'grain', in <b>%</b>."

[attributes.enable]
digest = "Enable the granular process"
description = "Enables/disables the granular process."
default = { value=0, type="float64", size=1 }

[attributes.random]
digest = "Enable random timing in the <m>rate</m>"
description = "Enable random timing variations in the <m>rate</m>."
default = { value=0, type="float64", size=1 }

[attributes.rate]
digest = "Rate of repetition"
description = "Rate of the repetition in <b>ms</b>."
default = { value=50, type="float64", size=1 }

[attributes.variation]
digest = "Amount of variation in each repetition"
description = "Amount of variation in each repeating 'grain', in <b>%</b>."
default = { value=0, type="float64", size=1 }