[object]
name = "sp.eraetouch"
module = "SP-Tools"
category = ""
digest = "Interface for the Erae Touch controller"
seealso =  ['sp.gridmatch', 'sp.corpusmatch', 'sp.corpusplayer~', 'sp.plotter']
description = "Interface for the Erae Touch controller."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.eraetouch</o> acts as the API parser to/from the Erae Touch as well as creating the LED feedback for multiple zones. You can connect this to <o>sp.gridmatch</o> for corpus-based sample playback or use the XYZ outputs directly for anything else in Max.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Dataset and control in"
description="Dataset (instance 1) and control input."

[inlets.1]
type="list"
digest="Dataset in (2)"
description="Dataset (instance 2) input."

[inlets.2]
type="list"
digest="Dataset in (3)"
description="Dataset (instance 3) input."

[inlets.3]
type="list"
digest="Dataset in (4)"
description="Dataset (instance 4) input."

[outlets]
[outlets.0]
type="list"
digest="XYZ position"
description="XYZ position from the Erae Touch or UI input."

[outlets.1]
type="list"
digest="<o>buffer~</o> out (1)"
description="<o>buffer~</o> (instance 1) output."

[outlets.2]
type="list"
digest="<o>buffer~</o> out (2)"
description="<o>buffer~</o> (instance 2) output."

[outlets.3]
type="list"
digest="<o>buffer~</o> out (3)"
description="<o>buffer~</o> (instance 3) output."

[outlets.4]
type="list"
digest="<o>buffer~</o> out (4)"
description="<o>buffer~</o> (instance 4) output."

[messages.load]
digest = "Load a pre-trained concat <b>.json</b> file"
description = "Opens file dialog to select pre-trained concat <b>.json</b> file."

[messages.read]
digest = "Read a pre-trained concat <b>.json</b> file"
description = "Reads a pre-trained concat <b>.json</b> file directly from a relative or absolute path."