[object]
name = "sp.folder"
module = "SP-Tools"
category = ""
digest = "A utility for looping through all the samples in a folder"
seealso =  ['sp.corpusanalysis', 'sp.corpusmatch', 'sp.corpusplayer~']
description = "A utility for looping through all the samples in a folder."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.folder</o> object is used in conjunction with <o>sp.corpusanalysis</o> to analyze every sample in a folder for the required descriptors and metadata.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="<b>Bang</o> to select folder to analyze"
description="<b>Bang</o> to select folder to analyze."

[inlets.1]
type="list"
digest="<b>Bang</o> to continue through loop "
description="<b>Bang</o> to continue analyzing through loop."

[outlets]
[outlets.0]
type="list"
digest="<b>Bang</o> when file is loaded"
description="<b>Bang</o> when file to be analyzed is loaded."

[outlets.1]
type="list"
digest="Total duration of analysis"
description="Total duration of analysis in <b>ms</b>."

[messages.load]
digest = "Load a pre-trained concat <b>.json</b> file"
description = "Opens file dialog to select pre-trained concat <b>.json</b> file."

[messages.read]
digest = "Read a pre-trained concat <b>.json</b> file"
description = "Reads a pre-trained concat <b>.json</b> file directly from a relative or absolute path."