[object]
name = "sp.melbandsrt~"
module = "SP-Tools"
category = ""
digest = "Analyzes audio for several audio desriptors based on audio input"
seealso =  ['sp.descriptorframe', 'sp.descriptors~', 'sp.descriptorsrt~', 'sp.melbandframe', 'sp.melbands~', 'sp.onsetframe~', 'sp.realtimeframe~']
description = "Analyzes audio for several audio desriptors based on audio input."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.melbandsrt~</o> object outputs 40 melbands which can be used for spectral compensation in corpused-based sample playback.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="signal"
digest="Audio and control in"
description="Audio input to analyze."

[outlets]
[outlets.0]
type="list"
digest="Melbands as list"
description="Analyzed melbands in list form."

[outlets.1]
type="list"
digest="Melbands as <o>buffer~</o>"
description="Analyzed melbands in <o>buffer~</o> form."

[messages.load]
digest = "Load a pre-trained concat <b>.json</b> file"
description = "Opens file dialog to select pre-trained concat <b>.json</b> file."

[messages.read]
digest = "Read a pre-trained concat <b>.json</b> file"
description = "Reads a pre-trained concat <b>.json</b> file directly from a relative or absolute path."