[object]
name = "sp.mfccframe"
module = "SP-Tools"
category = ""
digest = "Analyzes audio for MFCCs based on frame input"
seealso =  ['sp.descriptors~', 'sp.descriptorsrt~', 'sp.melbandframe', 'sp.melbands~', 'sp.melbandsrt~', 'sp.mfcc~', 'sp.mfccrt~', 'sp.onsetframe~', 'sp.realtimeframe~']
description = "Analyzes audio for MFCCs based on frame input."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.mfccframe</o> object outputs 13 MFCC coefficients (skipping the 0th coefficient) which can be used for classification and clustering. Although abstract they can also be used to control parameters.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Frame to analyze"
description="Frame to analyze from <o>sp.onsetframe~</o>."

[outlets]
[outlets.0]
type="list"
digest="MFCCs as list"
description="Analyzed MFCCs in list form."

[outlets.1]
type="list"
digest="MFCCs as <o>buffer~</o>"
description="Analyzed MFCCs in <o>buffer~</o> form."

[messages.load]
digest = "Load a pre-trained concat <b>.json</b> file"
description = "Opens file dialog to select pre-trained concat <b>.json</b> file."

[messages.read]
digest = "Read a pre-trained concat <b>.json</b> file"
description = "Reads a pre-trained concat <b>.json</b> file directly from a relative or absolute path."