[object]
name = "sp.novelty~"
module = "SP-Tools"
category = ""
digest = "Novelty-based onset detection"
seealso =  ['sp.onset~', 'sp.onsetframe', 'sp.realtimeframe~']
description = "Novelty-based onset detection."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.novelty~</o> object takes audio input and outputs a <b>bang</b> and a trigger when novelty is detected. The novelty can be computed across different time frames and for different parameters.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="signal"
digest="Audio and control in"
description="Audio input to analyze for novelty."

[outlets]
[outlets.0]
type="list"
digest="<b>bang</b> out"
description="<b>bang</b> output when novelty is detected."

[outlets.1]
type="signal"
digest="Trigger out"
description="Trigger output when novelty is detected."

[messages.load]
digest = "Load a pre-trained concat <b>.json</b> file"
description = "Opens file dialog to select pre-trained concat <b>.json</b> file."

[messages.read]
digest = "Read a pre-trained concat <b>.json</b> file"
description = "Reads a pre-trained concat <b>.json</b> file directly from a relative or absolute path."