[object]
name = "sp.ramp"
module = "SP-Tools"
category = ""
digest = "Event-based ramp generation"
seealso =  ['sp.ramp~', 'sp.onset~', 'sp.onsetframe', 'sp.novelty~']
description = "Event-based ramp generation."
discussion = """
    <h4><openfilelink filename="SP-Tools Overview.maxpat">Open the Overview Patch</openfilelink></h4>
    <p>The <o>sp.ramp</o> object takes onsets as input (as bangs or triggers/gates) and incrementally outputs three versions of a given ramp based on the amount of defined events.</p>
"""

[metadata]
author = "Rodrigo Constanzo, Flucoma Project"
tags = ['Machine Learning', 'Drums']

[inlets]
[inlets.0]
type="list"
digest="Onset and control input"
description="Incoming onsets (as bangs/triggers/gates) and control input."

[outlets]
[outlets.0]
type="float64"
digest="Forwards ramp output"
description="Forwards ramp output per event step."

[outlets.1]
type="float64"
digest="Backwards ramp output"
description="Backwards ramp output per event step."

[outlets.2]
type="float64"
digest="Palindrome ramp output"
description="Palindrome ramp output per event step."

[outlets.3]
type="float64"
digest="Current position"
description="Current position through the given ramp."

[messages.load]
digest = "Load a pre-trained concat <b>.json</b> file"
description = "Opens file dialog to select pre-trained concat <b>.json</b> file."

[messages.read]
digest = "Read a pre-trained concat <b>.json</b> file"
description = "Reads a pre-trained concat <b>.json</b> file directly from a relative or absolute path."